# Generated by Django 3.0.2 on 2020-03-20 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienttype',
                 models.CharField(choices=[('G', 'Guest'), ('E', 'Upwork'), ('F', 'Freelance'), ('C', 'Colleague')],
                                  max_length=20, verbose_name='Client Type')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phoneno', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
